version: '3'

services:
  database:
    image: postgres:14-alpine
    hostname: database
    restart: always
    ports:
      - 15432:5432
    environment:
      - POSTGRES_USER=stalkee
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=stalkee
    volumes:
      - db-data:/var/lib/postgresql/data

  bot:
    hostname: bot
    depends_on:
      - database
    build:
      context: .
      dockerfile: ./Dockerfile
    env_file: .env
    environment:
      - DB_URI=postgres://stalkee:password@database/stalkee

volumes:
  db-data:
